apiVersion: v1
kind: ConfigMap
metadata:
  name: sentinel-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sentinel.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.config }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: sentinel-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sentinel.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.secrets }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
